"""
crew_pipeline.py
The main crew pipeline that wires all agents together.
Assignment requirement: "One flow, end to end."
Runs in sequence:
  1. RFx Drafter → draft the RFx
  2. Vendor Dispatcher → send to 5 vendors (stubbed)
  3. Document Parser → read all responses
  4. Normalizer → normalize to same units/currency
  5. Analyst → ready for buyer Q&A
"""

import json
import os
import sys

from openai import OpenAI

# Add parent directory to path
sys.path.insert(0, os.path.dirname(__file__))

from agents.rfx_drafter import RFxDrafterAgent
from agents.vendor_dispatcher import VendorDispatcherAgent
from agents.document_parser import DocumentParserAgent
from agents.normalizer import NormalizerAgent, RFX_LINE_ITEMS
from agents.analyst import AnalystAgent

BASE_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(BASE_DIR, "data")
VENDOR_DIR = os.path.join(DATA_DIR, "vendor_responses")
OUTPUT_DIR = os.path.join(DATA_DIR, "rfx_output")


class RFxCrew:
    """
    Orchestrates the full RFx pipeline crew.
    Each agent has a single responsibility; this class wires them together.
    """

    def __init__(self, openai_api_key: str = None):
        api_key = openai_api_key or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise ValueError("OPENAI_API_KEY must be set (env var or passed directly)")

        self.client = OpenAI(api_key=api_key)

        # Initialize all agents
        self.drafter = RFxDrafterAgent(self.client)
        self.dispatcher = VendorDispatcherAgent(stub=True, log_dir=OUTPUT_DIR)
        self.parser = DocumentParserAgent(self.client)
        self.normalizer = NormalizerAgent(self.client)
        self.analyst = AnalystAgent(self.client)

        # Pipeline state
        self.rfx = None
        self.raw_extractions = []
        self.normalized_vendors = []
        self.comparison = None

    # ── Step 1: Draft RFx ────────────────────────────────────────────────────

    def load_rfx_from_file(self, path: str = None) -> dict:
        """Load an existing RFx JSON (generated by seed_data.py for the demo)."""
        path = path or os.path.join(OUTPUT_DIR, "RFX-2024-001.json")
        with open(path, "r", encoding="utf-8") as f:
            self.rfx = json.load(f)
        print(f"[Drafter] Loaded RFx: {self.rfx['rfx_id']} — {len(self.rfx['line_items'])} line items, "
              f"{len(self.rfx['vendors'])} vendors")
        return self.rfx

    def draft_rfx_interactively(self) -> dict:
        """Use the RFx Drafter agent in conversation mode."""
        print("[Drafter] Starting RFx co-pilot session...")
        rfx, reply = self.drafter.quick_draft("corrugated packaging")
        if rfx:
            self.rfx = rfx
            rfx_path = os.path.join(OUTPUT_DIR, f"{rfx.get('rfx_id', 'RFX-DRAFT')}.json")
            with open(rfx_path, "w", encoding="utf-8") as f:
                json.dump(rfx, f, indent=2, ensure_ascii=False)
            print(f"[Drafter] RFx drafted and saved: {rfx_path}")
        return rfx

    # ── Step 2: Dispatch to vendors ──────────────────────────────────────────

    def dispatch_rfx(self) -> list:
        """Send RFx to all vendors (stubbed SMTP)."""
        if not self.rfx:
            raise RuntimeError("No RFx loaded. Run load_rfx_from_file() first.")
        print(f"[Dispatcher] Sending RFx to {len(self.rfx['vendors'])} vendors (stubbed SMTP)...")
        results = self.dispatcher.dispatch(self.rfx)
        for r in results:
            print(f"  → {r['vendor_name']}: {r['status']} (saved: {os.path.basename(r.get('stub_path', ''))})")
        return results

    # ── Step 3: Parse vendor responses ───────────────────────────────────────

    def parse_vendor_responses(self) -> list:
        """
        Parse all vendor response files.
        Assignment: 'reads every response, whatever shape it arrives in'
        Real extraction — not hardcoded.
        """
        print(f"[Parser] Parsing vendor responses from: {VENDOR_DIR}")
        self.raw_extractions = self.parser.parse_all(VENDOR_DIR)
        print(f"[Parser] Parsed {len(self.raw_extractions)} vendor responses")
        for r in self.raw_extractions:
            n = len(r.get("line_items_raw", []))
            print(f"  {r.get('vendor_id', '?')} {r.get('vendor_name', '?')}: "
                  f"{n} lines extracted via {r.get('parse_method', '?')} "
                  f"(confidence: {r.get('confidence', '?')})")

        # Save raw extractions
        raw_path = os.path.join(OUTPUT_DIR, "raw_extractions.json")
        with open(raw_path, "w", encoding="utf-8") as f:
            json.dump(self.raw_extractions, f, indent=2, ensure_ascii=False)
        return self.raw_extractions

    # ── Step 4: Normalize ────────────────────────────────────────────────────

    def normalize(self) -> dict:
        """
        Normalize all vendor data to same currency, units, and line IDs.
        Assignment: 'same lines, same units, same currency'
        Handles ugly edges: USD quotes, per-100-pcs, missing lines.
        """
        print(f"[Normalizer] Normalizing {len(self.raw_extractions)} vendor extractions...")
        self.normalized_vendors = []
        for raw in self.raw_extractions:
            normalized = self.normalizer.normalize_vendor(raw)
            self.normalized_vendors.append(normalized)
            flags = normalized.get("vendor_flags", [])
            print(f"  {normalized['vendor_id']} {normalized['vendor_name']}: "
                  f"{len(normalized['lines'])} lines normalized"
                  + (f", {len(flags)} flags" if flags else ""))

        self.comparison = self.normalizer.build_comparison_matrix(self.normalized_vendors)

        # Save comparison
        comp_path = os.path.join(OUTPUT_DIR, "comparison_matrix.json")
        with open(comp_path, "w", encoding="utf-8") as f:
            json.dump(self.comparison, f, indent=2, ensure_ascii=False)
        print(f"[Normalizer] Comparison matrix saved: {comp_path}")
        print(f"[Normalizer] Qualified vendors (passed questionnaire): {self.comparison['qualified_vendors']}")
        return self.comparison

    # ── Step 5: Load analyst ─────────────────────────────────────────────────

    def load_analyst(self):
        """Load the comparison into the analyst agent for Q&A."""
        if not self.comparison:
            raise RuntimeError("No comparison built. Run normalize() first.")
        self.analyst.load_comparison(self.comparison)
        print("[Analyst] Comparison loaded. Ready for buyer questions.")

    # ── Full pipeline ─────────────────────────────────────────────────────────

    def run_full_pipeline(self, use_existing_rfx: bool = True) -> dict:
        """
        Run the complete pipeline end to end.
        Returns the comparison matrix ready for the UI.
        """
        print("\n" + "="*60)
        print("RFx CREW PIPELINE — Starting")
        print("="*60)

        # Step 1
        if use_existing_rfx:
            self.load_rfx_from_file()
        else:
            self.draft_rfx_interactively()

        # Step 2
        self.dispatch_rfx()

        # Step 3
        self.parse_vendor_responses()

        # Step 4
        self.normalize()

        # Step 5
        self.load_analyst()

        print("\n" + "="*60)
        print("PIPELINE COMPLETE — Buyer can now ask questions")
        print("="*60 + "\n")

        return self.comparison


def run_cli_demo():
    """Simple CLI demo: run the pipeline then enter Q&A loop."""
    import readline  # noqa: F401 — enables arrow keys in input()

    crew = RFxCrew()
    crew.run_full_pipeline(use_existing_rfx=True)

    print("\nEnter your questions about the vendor comparison.")
    print("Type 'award' for the full award recommendation, 'quit' to exit.\n")

    while True:
        try:
            q = input("Buyer: ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if not q:
            continue
        if q.lower() in ("quit", "exit", "q"):
            break
        if q.lower() == "award":
            answer = crew.analyst.get_award_recommendation()
        else:
            answer = crew.analyst.ask(q)
        print(f"\nAnalyst:\n{answer}\n")


if __name__ == "__main__":
    run_cli_demo()
